nopCommerce_4.50.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Controllers/AvalaraProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Tax.Avalara.Services;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Web.Areas.Admin.Controllers;

namespace Nop.Plugin.Tax.Avalara.Controllers
{
    public class AvalaraProductController : BaseAdminController
    {
        #region Fields

        private readonly AvalaraTaxManager _avalaraTaxManager;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ITaxPluginManager _taxPluginManager;

        #endregion

        #region Ctor

        public AvalaraProductController(AvalaraTaxManager avalaraTaxManager,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ITaxPluginManager taxPluginManager)
        {
            _avalaraTaxManager = avalaraTaxManager;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _taxPluginManager = taxPluginManager;
        }

        #endregion

        #region Methods

        [HttpPost]
        public async Task<IActionResult> ExportProducts(string selectedIds)
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
                return RedirectToAction("List", "Product");

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //export items
            var exportedItems = await _avalaraTaxManager.ExportProductsAsync(selectedIds);
            if (exportedItems.HasValue)
            {
                if (exportedItems > 0)
                    _notificationService.SuccessNotification(string.Format(await _localizationService.GetResourceAsync("Plugins.Tax.Avalara.Items.Export.Success"), exportedItems));
                else
                    _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Plugins.Tax.Avalara.Items.Export.AlreadyExported"));
            }
            else
                _notificationService.ErrorNotification(await _localizationService.GetResourceAsync("Plugins.Tax.Avalara.Items.Export.Error"));

            return RedirectToAction("List", "Product");
        }

        #endregion
    }
}

nopCommerce_4.50.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/ExportItems.cshtml
@{
    var button = await Html.PartialAsync("~/Plugins/Tax.Avalara/Views/Product/_ExportItemsButton.cshtml");
    var form = await Html.PartialAsync("~/Plugins/Tax.Avalara/Views/Product/_ExportItemsForm.cshtml");

    //we need to replace some specific symbols here
    var content = await form.RenderHtmlContentAsync();
    content = content.Replace("</script>", "<\\/script>");
    form = Html.Raw(content);
}

<script>
    $(document).ready(function () {
        $('#delete-selected').before(`@button`);
        $('#export-excel-selected-form').after(`@form`);
    });
</script>

nopCommerce_4.50.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/_ExportItemsButton.cshtml
<button type="button" id="export-avalara-selected" class="btn btn-warning" style="margin-right: 4px">
    <i class="fas fa-exchange-alt"></i>
    @T("Plugins.Tax.Avalara.Items.Export")
</button>

nopCommerce_4.50.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/_ExportItemsForm.cshtml
<form asp-controller="AvalaraProduct" asp-action="ExportProducts" method="post" id="export-avalara-selected-form">
    <script>
        $(document).ready(function () {
            $('#export-avalara-selected').click(function (e) {
                e.preventDefault();
                var ids = selectedIds.join(',');
                if (!ids) {
                    $('#export-avalara-selected-alert-info').text('@T("Admin.Products.NoProducts")');
                    $('#export-avalara-selected-alert').click();
                }
                else {
                    $('#export-avalara-selected-form #selectedIds').val(ids);
                    $('#export-avalara-selected-form').submit();
                    updateTable('#products-grid');
                }
                return false;
            });
        });
    </script>
    <nop-alert asp-alert-id="export-avalara-selected-alert" />
    <input type="hidden" id="selectedIds" name="selectedIds" value="" />
</form>